########################################
# Core / naming
########################################

variable "aws_region" {
  description = "AWS region to deploy into. ap-south-1 (Mumbai) is closest to KaramStay's userbase in India."
  type        = string
  default     = "ap-south-1"
}

variable "app_name" {
  description = "Short name used to prefix/tag all resources (e.g. \"karamstay\")."
  type        = string
  default     = "karamstay"
}

variable "environment" {
  description = "Deployment environment name, used in resource names, tags, and the SSM parameter path prefix (/{app_name}/{environment}/...)."
  type        = string
  default     = "prod"
}

########################################
# Custom domain / TLS
########################################

variable "domain_name" {
  description = <<-EOT
    Client-owned custom domain the App Runner service will be reachable at
    (e.g. "api.karamstay.com"). App Runner provisions and validates its own
    ACM certificate for this domain automatically — you don't supply a
    certificate ARN, you just add the DNS validation CNAME records that
    Terraform outputs after applying (see outputs.tf).
  EOT
  type        = string
}

variable "enable_www_subdomain" {
  description = "Whether App Runner should also provision/validate the www. subdomain of domain_name."
  type        = bool
  default     = false
}

########################################
# Alerting / budgets
########################################

variable "alert_email" {
  description = "Email address that receives AWS Budgets alerts (via SNS subscription). The subscription requires manual confirmation via a link emailed by AWS after the first apply."
  type        = string
}

variable "budget_threshold_low_usd" {
  description = "First (lowest) monthly cost threshold, in USD, that triggers a budget alert email."
  type        = number
  default     = 25
}

variable "budget_threshold_medium_usd" {
  description = "Second monthly cost threshold, in USD, that triggers a budget alert email."
  type        = number
  default     = 50
}

variable "budget_threshold_high_usd" {
  description = "Third (highest) monthly cost threshold, in USD, that triggers a budget alert email."
  type        = number
  default     = 75
}

variable "monthly_budget_limit_usd" {
  description = "The overall monthly budget amount tracked by AWS Budgets, in USD. Should be >= budget_threshold_high_usd."
  type        = number
  default     = 100
}

########################################
# WAF
########################################

variable "waf_rate_limit_requests" {
  description = "Max requests from a single IP within waf_rate_limit_window_seconds before AWS WAF starts blocking that IP in front of App Runner."
  type        = number
  default     = 700
}

variable "waf_rate_limit_window_seconds" {
  description = "Evaluation window (in seconds) for the WAF rate-based rule. AWS WAF supports 60, 120, 300, or 600."
  type        = number
  default     = 300
}

########################################
# Networking
########################################

variable "vpc_cidr" {
  description = "CIDR block for the VPC. Only used privately by RDS + the App Runner VPC connector; there is no NAT/IGW, so this never needs to be internet-routable."
  type        = string
  default     = "10.20.0.0/16"
}

variable "private_subnet_cidrs" {
  description = "CIDR blocks for the two private subnets (RDS subnet group + App Runner VPC connector), one per AZ."
  type        = list(string)
  default     = ["10.20.1.0/24", "10.20.2.0/24"]
}

########################################
# Database (RDS Postgres)
########################################

variable "db_instance_class" {
  description = "RDS instance class."
  type        = string
  default     = "db.t4g.small"
}

variable "db_engine_version" {
  description = "Postgres major/minor engine version for RDS."
  type        = string
  default     = "16"
}

variable "db_allocated_storage" {
  description = "Baseline provisioned storage for RDS, in GiB."
  type        = number
  default     = 30
}

variable "db_max_allocated_storage" {
  description = "Ceiling for RDS storage autoscaling, in GiB. Set equal to db_allocated_storage to disable autoscaling."
  type        = number
  default     = 200
}

variable "db_backup_retention_period" {
  description = "Number of days RDS automated backups are retained."
  type        = number
  default     = 7
}

variable "db_name" {
  description = "Initial database name created on the RDS instance."
  type        = string
  default     = "karamstay"
}

variable "db_username" {
  description = "Master username for the RDS instance. The master password is generated by Terraform (random_password) and never set by hand; it is written straight into the DATABASE_URL SSM parameter."
  type        = string
  default     = "karamstay"
}

########################################
# App Runner (compute)
########################################

variable "apprunner_cpu" {
  description = "App Runner instance CPU units. \"512\" = 0.5 vCPU."
  type        = string
  default     = "512"
}

variable "apprunner_memory" {
  description = "App Runner instance memory, in MB. \"1024\" = 1 GB."
  type        = string
  default     = "1024"
}

variable "apprunner_min_size" {
  description = "Minimum number of App Runner instances (auto scaling configuration MinSize)."
  type        = number
  default     = 1
}

variable "apprunner_max_size" {
  description = "Maximum number of App Runner instances (auto scaling configuration MaxSize)."
  type        = number
  default     = 4
}

variable "apprunner_max_concurrency" {
  description = "Maximum concurrent requests per App Runner instance before scaling out."
  type        = number
  default     = 100
}

variable "ecr_image_tag" {
  description = <<-EOT
    Image tag the aws_apprunner_service resource points at when Terraform
    creates/updates it. In steady state, the CI/CD pipeline (see
    .github/workflows/backend-ci-cd.yml) moves the running service onto new
    git-SHA tags via `aws apprunner start-deployment` / update-service calls
    directly, outside of Terraform, so this value only really matters for
    the very first `terraform apply` (bootstrapping the service) and for
    disaster-recovery re-applies.
  EOT
  type        = string
  default     = "latest"
}

########################################
# Observability
########################################

variable "cloudwatch_log_retention_days" {
  description = "Retention period, in days, for the App Runner CloudWatch log group."
  type        = number
  default     = 30
}

########################################
# Application configuration (non-secret)
#
# These map 1:1 to apps/backend/.env.example and app/core/config.py. They are
# passed to App Runner as plain runtime_environment_variables. Anything
# secret (DATABASE_URL, JWT_SECRET_KEY, WhatsApp token, Firebase service
# account JSON, ...) is provisioned as an SSM SecureString instead — see
# main.tf's `local.computed_secrets` / `local.external_secrets` and the
# aws_ssm_parameter resources.
########################################

variable "app_display_name" {
  description = "Human-readable app name, passed through as APP_NAME."
  type        = string
  default     = "KaramStay"
}

variable "jwt_algorithm" {
  description = "JWT signing algorithm."
  type        = string
  default     = "HS256"
}

variable "access_token_expire_minutes" {
  type    = number
  default = 15
}

variable "refresh_token_expire_days" {
  type    = number
  default = 30
}

variable "backend_cors_origins" {
  description = "JSON-encoded list of allowed CORS origins, e.g. [\"https://app.karamstay.com\"]."
  type        = string
  default     = "[]"
}

variable "whatsapp_api_base_url" {
  type    = string
  default = "https://graph.facebook.com/v20.0"
}

variable "s3_presigned_url_expire_seconds" {
  type    = number
  default = 300
}

variable "rate_limit_enabled" {
  type    = bool
  default = true
}

variable "otp_expire_minutes" {
  type    = number
  default = 10
}

variable "otp_length" {
  type    = number
  default = 6
}

variable "late_fee_grace_days" {
  type    = number
  default = 3
}

variable "late_fee_percent_per_day" {
  type    = string
  default = "1.0"
}

variable "invoice_generation_day" {
  type    = number
  default = 1
}

variable "app_log_level" {
  description = "Log level for the app/gunicorn process. Not currently read by app/core/config.py (extra=\"ignore\" makes this harmless) but wired through for when logging config lands."
  type        = string
  default     = "INFO"
}
